name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    env:
      Solution_Name: 'Blazor Lab Starter Code.sln'
      Test_Project_Path: 'LibApp.tests/LibApp.tests.csproj'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore Packages
      run: dotnet restore "${{ env.Solution_Name }}"

    - name: Build Solution
      run: dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore

    - name: Run Unit Tests
      run: dotnet test "${{ env.Test_Project_Path }}" --no-restore --verbosity normal

